2021-02-20 14:16:35 INFO run.py:219 GNS3 server version 2.2.17
2021-02-20 14:16:35 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-02-20 14:16:35 INFO run.py:224 Config file /home/saad/.config/GNS3/2.2/gns3_server.conf loaded
2021-02-20 14:16:35 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-02-20 14:16:35 INFO run.py:243 Running with Python 3.9.1 and has PID 22376
2021-02-20 14:16:35 INFO run.py:79 Current locale is en_US.UTF-8
2021-02-20 14:16:35 INFO web_server.py:318 Starting server on localhost:3080
2021-02-20 14:16:35 INFO __init__.py:62 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-02-20 14:16:35 INFO __init__.py:66 Controller is starting
2021-02-20 14:16:35 INFO compute.py:64 Create compute local
2021-02-20 14:16:35 INFO compute.py:364 Connecting to compute 'local'
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:35 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-02-20 14:16:35 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/templates HTTP/1.1" 200 13161 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:35 INFO notification_handler.py:73 New client has connected to controller WebSocket
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/appliances?symbol_theme=Affinity-square-red HTTP/1.1" 200 750664 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/projects HTTP/1.1" 200 6493 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:35 +0000] "GET /v2/projects HTTP/1.1" 200 6493 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:44 INFO project.py:78 Project 54200cb8-26b8-4929-8b2b-553020004955 with path '/home/saad/GNS3/projects/ntp' created
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects HTTP/1.1" 201 298 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO qemu_vm.py:201 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082] has set the QEMU path to /bin/qemu-system-x86_64
2021-02-20 14:16:44 INFO qemu_vm.py:603 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: MAC address changed to 0c:49:55:d0:82:00
2021-02-20 14:16:44 INFO qemu_vm.py:551 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: number of Ethernet adapters changed to 1
2021-02-20 14:16:44 INFO qemu_vm.py:128 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082] has been created
2021-02-20 14:16:44 INFO base_node.py:282 Qemu: S1 [73b6d391-5e52-4114-8286-8936a2e5d082] created
2021-02-20 14:16:44 INFO qemu_vm.py:551 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: number of Ethernet adapters changed to 8
2021-02-20 14:16:44 INFO qemu_vm.py:244 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082] has set the QEMU hda_disk_image path to /home/saad/GNS3/images/QEMU/vios_l2-adventerprisek9-m.03.2017.qcow2
2021-02-20 14:16:44 INFO qemu_vm.py:720 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082] has set the process priority to normal
2021-02-20 14:16:44 INFO qemu_vm.py:743 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082] has set the RAM to 768
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes HTTP/1.1" 201 1669 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO qemu_vm.py:201 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the QEMU path to /usr/sbin/qemu-system-i386
2021-02-20 14:16:44 INFO qemu_vm.py:603 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]: MAC address changed to 0c:49:55:fa:11:00
2021-02-20 14:16:44 INFO qemu_vm.py:551 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]: number of Ethernet adapters changed to 1
2021-02-20 14:16:44 INFO qemu_vm.py:128 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has been created
2021-02-20 14:16:44 INFO base_node.py:282 Qemu: R1 [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] created
2021-02-20 14:16:44 INFO qemu_vm.py:551 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]: number of Ethernet adapters changed to 8
2021-02-20 14:16:44 INFO qemu_vm.py:244 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the QEMU hda_disk_image path to /home/saad/GNS3/images/QEMU/vios-adventerprisek9-m.vmdk.SPA.156-2.T
2021-02-20 14:16:44 INFO qemu_vm.py:348 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the QEMU hda disk interface to virtio
2021-02-20 14:16:44 INFO qemu_vm.py:244 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the QEMU hdb_disk_image path to /home/saad/GNS3/images/QEMU/IOSv_startup_config.img
2021-02-20 14:16:44 INFO qemu_vm.py:371 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the QEMU hdb disk interface to virtio
2021-02-20 14:16:44 INFO qemu_vm.py:720 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the process priority to normal
2021-02-20 14:16:44 INFO qemu_vm.py:743 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11] has set the RAM to 512
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes HTTP/1.1" 201 1821 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO nat.py:51 NAT node 'NAT1' configured to use NAT interface 'virbr0'
2021-02-20 14:16:44 INFO base_node.py:655 Starting new uBridge hypervisor localhost:36879
2021-02-20 14:16:44 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:36879']
2021-02-20 14:16:44 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/builtin/63b15396-0475-4fc0-9f21-56892248ce0f/ubridge.log
2021-02-20 14:16:44 INFO hypervisor.py:179 ubridge started PID=22391
2021-02-20 14:16:44 INFO base_node.py:658 Hypervisor localhost:36879 has successfully started
2021-02-20 14:16:44 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:36879 after 0.1042 seconds
2021-02-20 14:16:44 INFO cloud.py:215 Cloud "NAT1" [63b15396-0475-4fc0-9f21-56892248ce0f] has been created
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO docker_vm.py:1058 Docker container "debian-1" [0e0f6f7c-2acd-4d08-a657-ea4121d2cfed]: number of Ethernet adapters changed to 1
2021-02-20 14:16:44 INFO docker_vm.py:406 Docker container 'debian-1' [0e0f6f7c-2acd-4d08-a657-ea4121d2cfed] created
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes HTTP/1.1" 201 919 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO qemu_vm.py:1346 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: NIO UDP added to adapter 1
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/adapters/1/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO qemu_vm.py:1346 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]: NIO UDP added to adapter 0
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/adapters/0/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO qemu_vm.py:1346 QEMU VM "R1" [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]: NIO UDP added to adapter 1
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/adapters/1/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO cloud.py:396 Cloud "NAT1" [63b15396-0475-4fc0-9f21-56892248ce0f]: NIO NIO UDP bound to port 0
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/63b15396-0475-4fc0-9f21-56892248ce0f/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:45 INFO docker_vm.py:960 Docker container 'debian-1' [0e0f6f7c-2acd-4d08-a657-ea4121d2cfed]: NIO UDP added to adapter 0
2021-02-20 14:16:45 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:45 INFO qemu_vm.py:1346 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: NIO UDP added to adapter 0
2021-02-20 14:16:45 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:45 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/adapters/0/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:45 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:44 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/open HTTP/1.1" 201 726 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:45 INFO project_handler.py:271 New client has connected to the notification stream for project ID '54200cb8-26b8-4929-8b2b-553020004955' (WebSocket method)
2021-02-20 14:16:45 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:45 +0000] "GET /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes HTTP/1.1" 200 15744 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:45 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:45 +0000] "GET /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 200 4118 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:45 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:45 +0000] "GET /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/drawings HTTP/1.1" 200 205 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:45 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:45 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:16:50 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:50 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/63b15396-0475-4fc0-9f21-56892248ce0f/start HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:51 INFO base_node.py:655 Starting new uBridge hypervisor localhost:34629
2021-02-20 14:16:51 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:34629']
2021-02-20 14:16:51 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/docker/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/ubridge.log
2021-02-20 14:16:51 INFO hypervisor.py:179 ubridge started PID=22494
2021-02-20 14:16:51 INFO base_node.py:658 Hypervisor localhost:34629 has successfully started
2021-02-20 14:16:51 INFO qemu_vm.py:1621 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/qemu-img.log
2021-02-20 14:16:51 INFO qemu_vm.py:1623 Executing qemu-img with: /usr/sbin/qemu-img check /home/saad/GNS3/images/QEMU/vios-adventerprisek9-m.vmdk.SPA.156-2.T
2021-02-20 14:16:51 INFO qemu_vm.py:1621 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/qemu-img.log
2021-02-20 14:16:51 INFO qemu_vm.py:1623 Executing qemu-img with: /bin/qemu-img check /home/saad/GNS3/images/QEMU/vios_l2-adventerprisek9-m.03.2017.qcow2
2021-02-20 14:16:51 INFO qemu_vm.py:1627 /usr/sbin/qemu-img returned with 0
2021-02-20 14:16:51 INFO qemu_vm.py:1627 /bin/qemu-img returned with 0
2021-02-20 14:16:51 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:34629 after 0.1027 seconds
2021-02-20 14:16:51 INFO qemu_vm.py:1621 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/qemu-img.log
2021-02-20 14:16:51 INFO qemu_vm.py:1623 Executing qemu-img with: /usr/sbin/qemu-img check /home/saad/GNS3/images/QEMU/IOSv_startup_config.img
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10006 and 10007
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10008 and 10009
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10010 and 10011
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10012 and 10013
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10014 and 10015
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10016 and 10017
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10018 and 10019
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'S1' [73b6d391-5e52-4114-8286-8936a2e5d082]:local UDP tunnel created between port 10020 and 10021
2021-02-20 14:16:51 INFO qemu_vm.py:1627 /usr/sbin/qemu-img returned with 63
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10022 and 10023
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10024 and 10025
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10026 and 10027
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10028 and 10029
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10030 and 10031
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10032 and 10033
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10034 and 10035
2021-02-20 14:16:51 INFO base_node.py:822 Qemu: 'R1' [b9afaf3b-8404-4fe2-ac5c-75a89a79fa11]:local UDP tunnel created between port 10036 and 10037
2021-02-20 14:16:51 INFO qemu_vm.py:1011 Starting QEMU with: /bin/qemu-system-x86_64 -name S1 -m 768M -smp cpus=1,sockets=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/hda_disk.qcow2,if=ide,index=0,media=disk,id=drive0 -uuid 73b6d391-5e52-4114-8286-8936a2e5d082 -serial telnet:127.0.0.1:5000,server,nowait -monitor tcp:127.0.0.1:35493,server,nowait -net none -device e1000,mac=0c:49:55:d0:82:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:49:55:d0:82:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -device e1000,mac=0c:49:55:d0:82:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10011,localaddr=127.0.0.1:10010 -device e1000,mac=0c:49:55:d0:82:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10013,localaddr=127.0.0.1:10012 -device e1000,mac=0c:49:55:d0:82:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10015,localaddr=127.0.0.1:10014 -device e1000,mac=0c:49:55:d0:82:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:49:55:d0:82:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:49:55:d0:82:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -display none
2021-02-20 14:16:51 INFO qemu_vm.py:1013 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/qemu.log
2021-02-20 14:16:51 INFO qemu_vm.py:1021 QEMU VM "S1" started PID=22574
2021-02-20 14:16:51 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38313
2021-02-20 14:16:51 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:38313']
2021-02-20 14:16:51 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/ubridge.log
2021-02-20 14:16:51 INFO hypervisor.py:179 ubridge started PID=22589
2021-02-20 14:16:51 INFO base_node.py:658 Hypervisor localhost:38313 has successfully started
2021-02-20 14:16:51 INFO qemu_vm.py:1011 Starting QEMU with: /usr/sbin/qemu-system-i386 -name R1 -m 512M -smp cpus=1,sockets=1 -enable-kvm -boot order=c -drive file=/home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -drive file=/home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/hdb_disk.qcow2,if=virtio,index=1,media=disk,id=drive1 -uuid b9afaf3b-8404-4fe2-ac5c-75a89a79fa11 -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:44399,server,nowait -net none -device e1000,mac=0c:49:55:fa:11:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -device e1000,mac=0c:49:55:fa:11:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10025,localaddr=127.0.0.1:10024 -device e1000,mac=0c:49:55:fa:11:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10027,localaddr=127.0.0.1:10026 -device e1000,mac=0c:49:55:fa:11:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10029,localaddr=127.0.0.1:10028 -device e1000,mac=0c:49:55:fa:11:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10031,localaddr=127.0.0.1:10030 -device e1000,mac=0c:49:55:fa:11:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10033,localaddr=127.0.0.1:10032 -device e1000,mac=0c:49:55:fa:11:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10035,localaddr=127.0.0.1:10034 -device e1000,mac=0c:49:55:fa:11:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10037,localaddr=127.0.0.1:10036 -display none
2021-02-20 14:16:51 INFO qemu_vm.py:1013 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/qemu.log
2021-02-20 14:16:51 INFO qemu_vm.py:1021 QEMU VM "R1" started PID=22602
2021-02-20 14:16:51 INFO base_node.py:655 Starting new uBridge hypervisor localhost:41489
2021-02-20 14:16:51 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:41489']
2021-02-20 14:16:51 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/ubridge.log
2021-02-20 14:16:51 INFO hypervisor.py:179 ubridge started PID=22606
2021-02-20 14:16:51 INFO base_node.py:658 Hypervisor localhost:41489 has successfully started
2021-02-20 14:16:51 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5012
2021-02-20 14:16:51 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:50 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:51 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38313 after 0.1016 seconds
2021-02-20 14:16:51 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:41489 after 0.1020 seconds
2021-02-20 14:16:51 INFO qemu_vm.py:1147 Connected to QEMU monitor on 127.0.0.1:35493 after 0.0107 seconds
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-2 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-3 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-4 off
2021-02-20 14:16:51 INFO qemu_vm.py:1147 Connected to QEMU monitor on 127.0.0.1:44399 after 0.0108 seconds
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-2 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-3 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-4 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-5 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-5 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-6 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-7 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-6 off
2021-02-20 14:16:51 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-7 off
2021-02-20 14:16:51 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:50 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/start HTTP/1.1" 200 3347 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:51 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:50 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/start HTTP/1.1" 200 3055 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:16:51 INFO web_log.py:233 ::1 [20/Feb/2021:09:16:50 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/start HTTP/1.1" 204 222 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:17:39 INFO web_log.py:233 ::1 [20/Feb/2021:09:17:39 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:18:11 INFO web_log.py:233 ::1 [20/Feb/2021:09:18:11 +0000] "GET /v2/gns3vm HTTP/1.1" 200 377 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:18:11 INFO web_log.py:233 ::1 [20/Feb/2021:09:18:11 +0000] "GET /v2/iou_license HTTP/1.1" 200 278 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:18:11 INFO __init__.py:62 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-02-20 14:18:11 INFO web_log.py:233 ::1 [20/Feb/2021:09:18:11 +0000] "GET /v2/gns3vm/engines HTTP/1.1" 200 1316 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:18:12 INFO __init__.py:572 Searching for VMware VMs in inventory file "/home/saad/.vmware/inventory.vmls"
2021-02-20 14:18:12 INFO web_log.py:233 ::1 [20/Feb/2021:09:18:11 +0000] "GET /v2/gns3vm/engines/vmware/vms HTTP/1.1" 200 401 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:15 INFO docker_vm.py:1005 Docker VM 'debian-1' [0e0f6f7c-2acd-4d08-a657-ea4121d2cfed]: tap-gns3-e0 removed from adapter 0
2021-02-20 14:21:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:15 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/adapters/0/ports/0/nio HTTP/1.1" 204 299 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:15 INFO qemu_vm.py:1162 Execute QEMU monitor command: set_link gns3-0 off
2021-02-20 14:21:15 INFO qemu_vm.py:1147 Connected to QEMU monitor on 127.0.0.1:35493 after 0.0105 seconds
2021-02-20 14:21:15 INFO qemu_vm.py:1399 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: NIO UDP removed from adapter 0
2021-02-20 14:21:15 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:21:15 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/adapters/0/ports/0/nio HTTP/1.1" 204 297 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:15 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/f06df4d1-ac6a-466f-9f5b-fdd9e6b581d1 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:17 INFO nat.py:51 NAT node 'NAT2' configured to use NAT interface 'virbr0'
2021-02-20 14:21:17 INFO base_node.py:655 Starting new uBridge hypervisor localhost:40667
2021-02-20 14:21:17 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:40667']
2021-02-20 14:21:17 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/builtin/22366f95-19fb-44e8-913c-93ff8448ded5/ubridge.log
2021-02-20 14:21:17 INFO hypervisor.py:179 ubridge started PID=23709
2021-02-20 14:21:17 INFO base_node.py:658 Hypervisor localhost:40667 has successfully started
2021-02-20 14:21:17 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:40667 after 0.1035 seconds
2021-02-20 14:21:17 INFO cloud.py:215 Cloud "NAT2" [22366f95-19fb-44e8-913c-93ff8448ded5] has been created
2021-02-20 14:21:18 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:17 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:18 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:17 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/df8f4ea9-33b7-3e96-86a2-c39bc9bb649c HTTP/1.1" 201 1573 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:18 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:21:18 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:18 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:18 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 1646 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:18 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:18 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:18 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:18 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 1646 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:18 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:18 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:20 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:21:20 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:20 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:20 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 1646 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:20 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:20 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:21 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:20 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 200 1646 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:21 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:21 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:25 INFO base_node.py:331 Builtin: 'NAT2' [22366f95-19fb-44e8-913c-93ff8448ded5]: is closing
2021-02-20 14:21:25 INFO base_node.py:669 Stopping uBridge hypervisor localhost:40667
2021-02-20 14:21:25 INFO hypervisor.py:208 Stopping uBridge process PID=23709
2021-02-20 14:21:25 INFO cloud.py:248 Cloud "NAT2" [22366f95-19fb-44e8-913c-93ff8448ded5] has been closed
2021-02-20 14:21:25 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:21:25 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:25 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:25 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/22366f95-19fb-44e8-913c-93ff8448ded5 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:29 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:29 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:21:29 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:29 INFO docker_vm.py:960 Docker container 'debian-1' [0e0f6f7c-2acd-4d08-a657-ea4121d2cfed]: NIO UDP added to adapter 0
2021-02-20 14:21:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:29 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:29 INFO qemu_vm.py:1162 Execute QEMU monitor command: set_link gns3-0 on
2021-02-20 14:21:29 INFO qemu_vm.py:1147 Connected to QEMU monitor on 127.0.0.1:35493 after 0.0112 seconds
2021-02-20 14:21:29 INFO qemu_vm.py:1346 QEMU VM "S1" [73b6d391-5e52-4114-8286-8936a2e5d082]: NIO UDP added to adapter 0
2021-02-20 14:21:29 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:21:29 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/adapters/0/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:21:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:29 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:29 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1290 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:21:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:21:29 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:22:44 INFO web_log.py:233 ::1 [20/Feb/2021:09:22:44 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:28:16 INFO web_log.py:233 ::1 [20/Feb/2021:09:28:16 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:31:52 INFO web_log.py:233 ::1 [20/Feb/2021:09:31:52 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:38:59 INFO web_log.py:233 ::1 [20/Feb/2021:09:38:59 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:39:01 INFO web_log.py:233 ::1 [20/Feb/2021:09:39:01 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:43:53 INFO web_log.py:233 ::1 [20/Feb/2021:09:43:53 +0000] "GET /v2/symbols HTTP/1.1" 200 60462 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:44:03 INFO base_manager.py:604 Writing image file to '/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin'
2021-02-20 14:44:07 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:03 +0000] "POST /v2/compute/iou/images/i86bi-linux-l2-adventerprisek9-15.2d.bin HTTP/1.1" 204 221 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:44:07 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:03 +0000] "POST /v2/computes/local/iou/images/i86bi-linux-l2-adventerprisek9-15.2d.bin HTTP/1.1" 200 219 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:44:09 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:09 +0000] "POST /v2/templates HTTP/1.1" 201 843 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'parrotlogo.png', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'mgmt_station.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'fortinet.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'ostinato-3d-icon.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'firefox.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'vRIN.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'vyos.png', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'cisco-fmcv.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'juniper-vmx.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'loadbalancer.svg', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'packetfence2.png', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'shieldedtux.png', returning default symbol...
2021-02-20 14:44:10 WARNING symbols.py:135 Could not retrieve symbol 'microsoft.svg', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'juniper-vqfx.svg', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'cisco-ise.svg', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'mgmt_station_docker.svg', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'rpi.png', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'opennac.png', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'pan-vm-fw.svg', returning default symbol...
2021-02-20 14:44:11 WARNING symbols.py:135 Could not retrieve symbol 'securityonion-logo.png', returning default symbol...
2021-02-20 14:44:24 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:24 +0000] "GET /v2/symbols HTTP/1.1" 200 60462 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:44:30 INFO base_manager.py:604 Writing image file to '/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin'
2021-02-20 14:44:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:30 +0000] "POST /v2/compute/iou/images/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin HTTP/1.1" 204 221 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:44:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:30 +0000] "POST /v2/computes/local/iou/images/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin HTTP/1.1" 200 219 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:44:36 INFO web_log.py:233 ::1 [20/Feb/2021:09:44:36 +0000] "POST /v2/templates HTTP/1.1" 201 838 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:22 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:22 +0000] "PUT /v2/templates/34cf1803-742f-4c79-8ba2-49a052717ac0 HTTP/1.1" 200 838 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:30 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:30 +0000] "PUT /v2/templates/bb5c6303-0270-4d7b-9f57-cd8256828547 HTTP/1.1" 200 846 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:32 INFO iou_vm.py:73 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: assigned with application ID 1
2021-02-20 14:45:32 INFO iou_vm.py:848 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: number of Ethernet adapters changed to 2
2021-02-20 14:45:32 INFO iou_vm.py:876 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: number of Serial adapters changed to 2
2021-02-20 14:45:32 INFO iou_vm.py:316 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: NVRAM updated from 128KB to 16KB
2021-02-20 14:45:32 INFO iou_vm.py:848 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: number of Ethernet adapters changed to 4
2021-02-20 14:45:32 INFO iou_vm.py:876 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: number of Serial adapters changed to 0
2021-02-20 14:45:32 INFO iou_vm.py:145 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 14:45:32 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:32 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 862 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:45:32 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:32 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/bb5c6303-0270-4d7b-9f57-cd8256828547 HTTP/1.1" 201 5993 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:32 INFO iou_vm.py:145 IOU "IOU1" [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 14:45:32 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:45:32 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/692c2297-eccc-4da0-a4a8-6477d8f74fb2 HTTP/1.1" 200 867 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:45:32 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:32 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/692c2297-eccc-4da0-a4a8-6477d8f74fb2 HTTP/1.1" 200 6065 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:33 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:33 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:35 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmpai31pdf9/iourc'
2021-02-20 14:45:35 ERROR route.py:217 Node error detected: IOUError
Traceback (most recent call last):
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/handlers/api/compute/iou_handler.py", line 194, in start
    await vm.start()
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/iou/iou_vm.py", line 520, in start
    await self._check_iou_licence()
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/iou/iou_vm.py", line 457, in _check_iou_licence
    raise IOUError("Invalid IOU license key {} detected in iourc file {} for host {}".format(user_ioukey,
gns3server.compute.iou.iou_error.IOUError: Invalid IOU license key 7cf4297c9ed898e4 detected in iourc file /tmp/tmpai31pdf9/iourc for host latitude
2021-02-20 14:45:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:35 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/692c2297-eccc-4da0-a4a8-6477d8f74fb2/start HTTP/1.1" 409 409 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:45:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:35 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/692c2297-eccc-4da0-a4a8-6477d8f74fb2/start HTTP/1.1" 409 368 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:45:40 INFO base_node.py:331 IOU: 'IOU1' [692c2297-eccc-4da0-a4a8-6477d8f74fb2]: is closing
2021-02-20 14:45:40 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:45:40 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/692c2297-eccc-4da0-a4a8-6477d8f74fb2 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:45:40 INFO web_log.py:233 ::1 [20/Feb/2021:09:45:40 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/692c2297-eccc-4da0-a4a8-6477d8f74fb2 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:49:25 INFO web_log.py:233 ::1 [20/Feb/2021:09:49:25 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:26 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:26 +0000] "GET /v2/gns3vm HTTP/1.1" 200 377 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:26 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:26 +0000] "GET /v2/iou_license HTTP/1.1" 200 278 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:26 INFO __init__.py:62 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-02-20 14:51:26 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:26 +0000] "GET /v2/gns3vm/engines HTTP/1.1" 200 1316 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:27 INFO __init__.py:572 Searching for VMware VMs in inventory file "/home/saad/.vmware/inventory.vmls"
2021-02-20 14:51:27 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:26 +0000] "GET /v2/gns3vm/engines/vmware/vms HTTP/1.1" 200 401 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:34 INFO __init__.py:62 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-02-20 14:51:34 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:34 +0000] "PUT /v2/iou_license HTTP/1.1" 201 283 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:36 INFO iou_vm.py:73 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: assigned with application ID 1
2021-02-20 14:51:36 INFO iou_vm.py:848 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: number of Ethernet adapters changed to 2
2021-02-20 14:51:36 INFO iou_vm.py:876 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: number of Serial adapters changed to 2
2021-02-20 14:51:36 INFO iou_vm.py:316 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: NVRAM updated from 128KB to 16KB
2021-02-20 14:51:36 INFO iou_vm.py:848 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: number of Ethernet adapters changed to 4
2021-02-20 14:51:36 INFO iou_vm.py:876 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: number of Serial adapters changed to 0
2021-02-20 14:51:36 INFO iou_vm.py:145 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 14:51:36 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:36 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 862 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:51:36 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:36 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/bb5c6303-0270-4d7b-9f57-cd8256828547 HTTP/1.1" 201 5993 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:36 INFO iou_vm.py:145 IOU "IOU1" [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 14:51:36 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:51:36 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/a15fd2af-6d85-45e3-9a5e-00336aed4f11 HTTP/1.1" 200 867 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:51:36 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:36 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/a15fd2af-6d85-45e3-9a5e-00336aed4f11 HTTP/1.1" 200 6065 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:38 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp46i5f1uh/iourc'
2021-02-20 14:51:38 INFO base_node.py:655 Starting new uBridge hypervisor localhost:44379
2021-02-20 14:51:38 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:44379']
2021-02-20 14:51:38 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/a15fd2af-6d85-45e3-9a5e-00336aed4f11/ubridge.log
2021-02-20 14:51:38 INFO hypervisor.py:179 ubridge started PID=49519
2021-02-20 14:51:38 INFO base_node.py:658 Hypervisor localhost:44379 has successfully started
2021-02-20 14:51:38 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:44379 after 0.1027 seconds
2021-02-20 14:51:39 INFO iou_vm.py:753 IOU IOU1 [id=a15fd2af-6d85-45e3-9a5e-00336aed4f11]: NETMAP file created
2021-02-20 14:51:39 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin', '-e', '4', '-s', '0', '1']
2021-02-20 14:51:39 INFO iou_vm.py:560 IOU instance a15fd2af-6d85-45e3-9a5e-00336aed4f11 started PID=49524
2021-02-20 14:51:39 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:38 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/a15fd2af-6d85-45e3-9a5e-00336aed4f11/start HTTP/1.1" 200 952 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:51:39 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:38 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/a15fd2af-6d85-45e3-9a5e-00336aed4f11/start HTTP/1.1" 200 6150 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:39 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:39 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:51:47 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/a15fd2af-6d85-45e3-9a5e-00336aed4f11/startup-config.cfg
2021-02-20 14:51:47 INFO web_log.py:233 ::1 [20/Feb/2021:09:51:47 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:54:43 INFO web_log.py:233 ::1 [20/Feb/2021:09:54:43 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:56:52 INFO base_node.py:331 IOU: 'IOU1' [a15fd2af-6d85-45e3-9a5e-00336aed4f11]: is closing
2021-02-20 14:56:52 INFO base_node.py:669 Stopping uBridge hypervisor localhost:44379
2021-02-20 14:56:52 INFO hypervisor.py:208 Stopping uBridge process PID=49519
2021-02-20 14:56:52 INFO iou_vm.py:698 Stopping IOU process for IOU VM "IOU1" PID=49524
2021-02-20 14:56:52 INFO iou_vm.py:698 Stopping IOU process for IOU VM "IOU1" PID=49524
2021-02-20 14:56:52 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/a15fd2af-6d85-45e3-9a5e-00336aed4f11/startup-config.cfg
2021-02-20 14:56:52 INFO web_log.py:233 ::1 [20/Feb/2021:09:56:52 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/a15fd2af-6d85-45e3-9a5e-00336aed4f11 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:56:52 INFO web_log.py:233 ::1 [20/Feb/2021:09:56:52 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/a15fd2af-6d85-45e3-9a5e-00336aed4f11 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:56:53 INFO web_log.py:233 ::1 [20/Feb/2021:09:56:53 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:08 INFO iou_vm.py:73 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: assigned with application ID 1
2021-02-20 14:57:08 INFO iou_vm.py:848 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: number of Ethernet adapters changed to 2
2021-02-20 14:57:08 INFO iou_vm.py:876 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: number of Serial adapters changed to 2
2021-02-20 14:57:08 INFO iou_vm.py:316 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: NVRAM updated from 128KB to 64KB
2021-02-20 14:57:08 INFO iou_vm.py:145 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 14:57:08 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:08 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 865 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:08 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:08 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/34cf1803-742f-4c79-8ba2-49a052717ac0 HTTP/1.1" 201 6703 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:08 INFO iou_vm.py:145 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 14:57:08 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:57:08 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 200 870 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:08 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:08 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 200 6776 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:11 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp8gpxjy7r/iourc'
2021-02-20 14:57:11 INFO base_node.py:655 Starting new uBridge hypervisor localhost:33229
2021-02-20 14:57:11 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:33229']
2021-02-20 14:57:11 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/6421b768-7f50-4d1c-aee5-40353a1d24b9/ubridge.log
2021-02-20 14:57:11 INFO hypervisor.py:179 ubridge started PID=50962
2021-02-20 14:57:11 INFO base_node.py:658 Hypervisor localhost:33229 has successfully started
2021-02-20 14:57:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:33229 after 0.1017 seconds
2021-02-20 14:57:11 INFO iou_vm.py:753 IOU R2 [id=6421b768-7f50-4d1c-aee5-40353a1d24b9]: NETMAP file created
2021-02-20 14:57:11 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin', '1']
2021-02-20 14:57:11 INFO iou_vm.py:560 IOU instance 6421b768-7f50-4d1c-aee5-40353a1d24b9 started PID=50967
2021-02-20 14:57:11 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:11 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9/start HTTP/1.1" 200 950 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:11 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:11 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9/start HTTP/1.1" 200 6856 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:21 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/6421b768-7f50-4d1c-aee5-40353a1d24b9/startup-config.cfg
2021-02-20 14:57:21 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:21 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:29 INFO iou_vm.py:145 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 14:57:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:29 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 200 944 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:29 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 200 6850 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:29 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:29 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:34 INFO nat.py:51 NAT node 'NAT2' configured to use NAT interface 'virbr0'
2021-02-20 14:57:34 INFO base_node.py:655 Starting new uBridge hypervisor localhost:39613
2021-02-20 14:57:34 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:39613']
2021-02-20 14:57:34 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/builtin/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/ubridge.log
2021-02-20 14:57:34 INFO hypervisor.py:179 ubridge started PID=50991
2021-02-20 14:57:34 INFO base_node.py:658 Hypervisor localhost:39613 has successfully started
2021-02-20 14:57:34 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:39613 after 0.1028 seconds
2021-02-20 14:57:34 INFO cloud.py:215 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74] has been created
2021-02-20 14:57:34 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:57:34 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:34 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:34 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/df8f4ea9-33b7-3e96-86a2-c39bc9bb649c HTTP/1.1" 201 1574 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:34 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:34 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:34 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:34 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74 HTTP/1.1" 200 1647 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:34 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:57:34 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:34 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:34 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74 HTTP/1.1" 200 1647 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:35 INFO iou_vm.py:145 IOU "R2" [6421b768-7f50-4d1c-aee5-40353a1d24b9]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 14:57:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:35 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 200 944 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:35 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:35 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 200 6849 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:36 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:36 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:57:56 INFO base_node.py:331 IOU: 'R2' [6421b768-7f50-4d1c-aee5-40353a1d24b9]: is closing
2021-02-20 14:57:56 INFO base_node.py:669 Stopping uBridge hypervisor localhost:33229
2021-02-20 14:57:56 INFO hypervisor.py:208 Stopping uBridge process PID=50962
2021-02-20 14:57:56 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R2" PID=50967
2021-02-20 14:57:56 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R2" PID=50967
2021-02-20 14:57:56 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/6421b768-7f50-4d1c-aee5-40353a1d24b9/startup-config.cfg
2021-02-20 14:57:56 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:56 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:57:56 INFO web_log.py:233 ::1 [20/Feb/2021:09:57:56 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/6421b768-7f50-4d1c-aee5-40353a1d24b9 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:00 INFO iou_vm.py:73 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: assigned with application ID 1
2021-02-20 14:58:00 INFO iou_vm.py:848 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: number of Ethernet adapters changed to 2
2021-02-20 14:58:00 INFO iou_vm.py:876 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: number of Serial adapters changed to 2
2021-02-20 14:58:00 INFO iou_vm.py:316 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: NVRAM updated from 128KB to 64KB
2021-02-20 14:58:00 INFO iou_vm.py:145 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 14:58:00 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:58:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 865 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:00 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:00 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/34cf1803-742f-4c79-8ba2-49a052717ac0 HTTP/1.1" 201 6702 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:00 INFO iou_vm.py:145 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 14:58:00 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:00 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/9688e111-6881-4420-b903-0f10f7c18244 HTTP/1.1" 200 870 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:00 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:00 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/9688e111-6881-4420-b903-0f10f7c18244 HTTP/1.1" 200 6775 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:01 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:01 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:15 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:15 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:58:15 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:15 INFO iou_vm.py:902 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: NIO UDP added to 0/0
2021-02-20 14:58:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:15 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/9688e111-6881-4420-b903-0f10f7c18244/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:15 INFO cloud.py:396 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: NIO NIO UDP bound to port 0
2021-02-20 14:58:15 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:58:15 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:15 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:15 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/6b680897-0990-4809-86e0-a748c304c68d HTTP/1.1" 201 1290 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:15 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:15 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/6b680897-0990-4809-86e0-a748c304c68d HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:17 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp9hmawcrw/iourc'
2021-02-20 14:58:17 INFO base_node.py:655 Starting new uBridge hypervisor localhost:41767
2021-02-20 14:58:17 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:41767']
2021-02-20 14:58:17 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/9688e111-6881-4420-b903-0f10f7c18244/ubridge.log
2021-02-20 14:58:17 INFO hypervisor.py:179 ubridge started PID=51051
2021-02-20 14:58:17 INFO base_node.py:658 Hypervisor localhost:41767 has successfully started
2021-02-20 14:58:17 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:41767 after 0.1034 seconds
2021-02-20 14:58:17 INFO iou_vm.py:753 IOU R2 [id=9688e111-6881-4420-b903-0f10f7c18244]: NETMAP file created
2021-02-20 14:58:17 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin', '1']
2021-02-20 14:58:17 INFO iou_vm.py:560 IOU instance 9688e111-6881-4420-b903-0f10f7c18244 started PID=51056
2021-02-20 14:58:17 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:17 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/9688e111-6881-4420-b903-0f10f7c18244/start HTTP/1.1" 200 950 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 14:58:17 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:17 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/9688e111-6881-4420-b903-0f10f7c18244/start HTTP/1.1" 200 6855 "-" "GNS3 QT Client v2.2.17"
2021-02-20 14:58:27 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/9688e111-6881-4420-b903-0f10f7c18244/startup-config.cfg
2021-02-20 14:58:28 INFO web_log.py:233 ::1 [20/Feb/2021:09:58:28 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:01:47 INFO web_log.py:233 ::1 [20/Feb/2021:10:01:47 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:03:12 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/9688e111-6881-4420-b903-0f10f7c18244/startup-config.cfg
2021-02-20 15:03:12 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/9688e111-6881-4420-b903-0f10f7c18244/private-config.cfg
2021-02-20 15:04:03 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:03 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:41 INFO iou_vm.py:975 IOU "R2" [9688e111-6881-4420-b903-0f10f7c18244]: NIO UDP removed from 0/0
2021-02-20 15:04:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:41 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/9688e111-6881-4420-b903-0f10f7c18244/adapters/0/ports/0/nio HTTP/1.1" 204 296 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:41 INFO cloud.py:449 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: NIO NIO UDP removed from port 0
2021-02-20 15:04:41 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:04:41 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/adapters/0/ports/0/nio HTTP/1.1" 204 296 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:41 INFO base_node.py:331 IOU: 'R2' [9688e111-6881-4420-b903-0f10f7c18244]: is closing
2021-02-20 15:04:41 INFO base_node.py:669 Stopping uBridge hypervisor localhost:41767
2021-02-20 15:04:41 INFO hypervisor.py:208 Stopping uBridge process PID=51051
2021-02-20 15:04:41 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R2" PID=51056
2021-02-20 15:04:41 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R2" PID=51056
2021-02-20 15:04:41 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/9688e111-6881-4420-b903-0f10f7c18244/startup-config.cfg
2021-02-20 15:04:41 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/9688e111-6881-4420-b903-0f10f7c18244/private-config.cfg
2021-02-20 15:04:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:41 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/9688e111-6881-4420-b903-0f10f7c18244 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:41 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/9688e111-6881-4420-b903-0f10f7c18244 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:43 INFO iou_vm.py:73 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: assigned with application ID 1
2021-02-20 15:04:43 INFO iou_vm.py:848 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: number of Ethernet adapters changed to 2
2021-02-20 15:04:43 INFO iou_vm.py:876 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: number of Serial adapters changed to 2
2021-02-20 15:04:43 INFO iou_vm.py:316 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: NVRAM updated from 128KB to 16KB
2021-02-20 15:04:43 INFO iou_vm.py:848 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: number of Ethernet adapters changed to 4
2021-02-20 15:04:43 INFO iou_vm.py:876 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: number of Serial adapters changed to 0
2021-02-20 15:04:43 INFO iou_vm.py:145 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 15:04:43 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:04:43 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 862 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:43 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:43 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/bb5c6303-0270-4d7b-9f57-cd8256828547 HTTP/1.1" 201 5992 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:43 INFO iou_vm.py:145 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 15:04:43 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:43 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5494a721-607d-408b-a3c9-99cc0502931d HTTP/1.1" 200 867 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:43 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:43 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5494a721-607d-408b-a3c9-99cc0502931d HTTP/1.1" 200 6064 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:44 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:44 INFO iou_vm.py:145 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin"
2021-02-20 15:04:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:04:44 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5494a721-607d-408b-a3c9-99cc0502931d HTTP/1.1" 200 867 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:44 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5494a721-607d-408b-a3c9-99cc0502931d HTTP/1.1" 200 6064 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:45 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmpawqcsq4q/iourc'
2021-02-20 15:04:45 INFO base_node.py:655 Starting new uBridge hypervisor localhost:44311
2021-02-20 15:04:45 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:44311']
2021-02-20 15:04:45 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/ubridge.log
2021-02-20 15:04:45 INFO hypervisor.py:179 ubridge started PID=52846
2021-02-20 15:04:45 INFO base_node.py:658 Hypervisor localhost:44311 has successfully started
2021-02-20 15:04:46 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:44311 after 0.1031 seconds
2021-02-20 15:04:46 INFO iou_vm.py:753 IOU IOU1 [id=5494a721-607d-408b-a3c9-99cc0502931d]: NETMAP file created
2021-02-20 15:04:46 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin', '-e', '4', '-s', '0', '1']
2021-02-20 15:04:46 INFO iou_vm.py:560 IOU instance 5494a721-607d-408b-a3c9-99cc0502931d started PID=52851
2021-02-20 15:04:46 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:45 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5494a721-607d-408b-a3c9-99cc0502931d/start HTTP/1.1" 200 952 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:46 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:45 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5494a721-607d-408b-a3c9-99cc0502931d/start HTTP/1.1" 200 6149 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:52 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/startup-config.cfg
2021-02-20 15:04:52 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:52 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:55 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:55 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:55 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:04:55 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:55 INFO iou_vm.py:902 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: NIO UDP added to 0/0
2021-02-20 15:04:55 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:55 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5494a721-607d-408b-a3c9-99cc0502931d/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:55 INFO cloud.py:396 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: NIO NIO UDP bound to port 0
2021-02-20 15:04:55 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:04:55 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:04:55 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:55 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:55 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:55 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/180f3fb4-cca1-42e4-a780-404222dd4dd5 HTTP/1.1" 201 1290 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:04:55 INFO web_log.py:233 ::1 [20/Feb/2021:10:04:55 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/180f3fb4-cca1-42e4-a780-404222dd4dd5 HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:05:52 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/startup-config.cfg
2021-02-20 15:05:52 INFO web_log.py:233 ::1 [20/Feb/2021:10:05:52 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:06:14 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/startup-config.cfg
2021-02-20 15:06:14 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/private-config.cfg
2021-02-20 15:06:14 INFO web_log.py:233 ::1 [20/Feb/2021:10:06:14 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:08:03 INFO web_log.py:233 ::1 [20/Feb/2021:10:08:03 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:08:05 INFO web_log.py:233 ::1 [20/Feb/2021:10:08:05 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:09:00 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/startup-config.cfg
2021-02-20 15:09:00 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/private-config.cfg
2021-02-20 15:09:01 INFO web_log.py:233 ::1 [20/Feb/2021:10:09:01 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:13:02 INFO web_log.py:233 ::1 [20/Feb/2021:10:13:02 +0000] "DELETE /v2/templates/bb5c6303-0270-4d7b-9f57-cd8256828547 HTTP/1.1" 204 212 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:13:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:13:33 +0000] "GET /v2/symbols HTTP/1.1" 200 60462 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:14:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:14:33 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:17:44 INFO base_manager.py:604 Writing image file to '/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin'
2021-02-20 15:17:47 INFO web_log.py:233 ::1 [20/Feb/2021:10:17:44 +0000] "POST /v2/compute/iou/images/i86bi-linux-l2-adventerprisek9-15.2d.bin HTTP/1.1" 204 221 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:17:47 INFO web_log.py:233 ::1 [20/Feb/2021:10:17:44 +0000] "POST /v2/computes/local/iou/images/i86bi-linux-l2-adventerprisek9-15.2d.bin HTTP/1.1" 200 219 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:17:47 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:17:47 +0000] "GET /v2/compute/iou/images HTTP/1.1" 200 647 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:17:47 INFO web_log.py:233 ::1 [20/Feb/2021:10:17:47 +0000] "GET /v2/computes/local/iou/images HTTP/1.1" 200 668 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:18:16 INFO web_log.py:233 ::1 [20/Feb/2021:10:18:16 +0000] "GET /v2/gns3vm HTTP/1.1" 200 377 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:18:16 INFO web_log.py:233 ::1 [20/Feb/2021:10:18:16 +0000] "GET /v2/iou_license HTTP/1.1" 200 278 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:18:16 INFO __init__.py:62 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-02-20 15:18:16 INFO web_log.py:233 ::1 [20/Feb/2021:10:18:16 +0000] "GET /v2/gns3vm/engines HTTP/1.1" 200 1316 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:18:16 INFO __init__.py:572 Searching for VMware VMs in inventory file "/home/saad/.vmware/inventory.vmls"
2021-02-20 15:18:16 INFO web_log.py:233 ::1 [20/Feb/2021:10:18:16 +0000] "GET /v2/gns3vm/engines/vmware/vms HTTP/1.1" 200 401 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:18:24 INFO web_log.py:233 ::1 [20/Feb/2021:10:18:24 +0000] "GET /v2/compute/iou/images HTTP/1.1" 200 647 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:18:24 INFO web_log.py:233 ::1 [20/Feb/2021:10:18:24 +0000] "GET /v2/computes/local/iou/images HTTP/1.1" 200 668 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:19:14 INFO web_log.py:233 ::1 [20/Feb/2021:10:19:14 +0000] "POST /v2/templates HTTP/1.1" 201 862 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:19:15 INFO web_log.py:233 ::1 [20/Feb/2021:10:19:15 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:19:34 INFO web_log.py:233 ::1 [20/Feb/2021:10:19:34 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:20:23 INFO iou_vm.py:73 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: assigned with application ID 2
2021-02-20 15:20:23 INFO iou_vm.py:848 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: number of Ethernet adapters changed to 2
2021-02-20 15:20:23 INFO iou_vm.py:876 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: number of Serial adapters changed to 2
2021-02-20 15:20:23 INFO iou_vm.py:316 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: NVRAM updated from 128KB to 16KB
2021-02-20 15:20:23 INFO iou_vm.py:848 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: number of Ethernet adapters changed to 4
2021-02-20 15:20:23 INFO iou_vm.py:876 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: number of Serial adapters changed to 0
2021-02-20 15:20:24 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:23 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 862 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:20:24 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:23 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/2d17c91c-ad2a-4874-bc5f-f01a6dde9b18 HTTP/1.1" 201 5991 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:20:24 INFO iou_vm.py:145 IOU "IOU2" [21dd9f92-3916-4d07-8460-c7effcf0f42c]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin"
2021-02-20 15:20:24 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:20:24 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/21dd9f92-3916-4d07-8460-c7effcf0f42c HTTP/1.1" 200 867 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:20:24 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:24 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/21dd9f92-3916-4d07-8460-c7effcf0f42c HTTP/1.1" 200 6063 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:20:28 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmpys69mu56/iourc'
2021-02-20 15:20:28 INFO base_node.py:655 Starting new uBridge hypervisor localhost:37399
2021-02-20 15:20:28 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:37399']
2021-02-20 15:20:28 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/21dd9f92-3916-4d07-8460-c7effcf0f42c/ubridge.log
2021-02-20 15:20:28 INFO hypervisor.py:179 ubridge started PID=55225
2021-02-20 15:20:28 INFO base_node.py:658 Hypervisor localhost:37399 has successfully started
2021-02-20 15:20:28 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:37399 after 0.1030 seconds
2021-02-20 15:20:28 INFO iou_vm.py:753 IOU IOU2 [id=21dd9f92-3916-4d07-8460-c7effcf0f42c]: NETMAP file created
2021-02-20 15:20:28 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin', '-e', '4', '-s', '0', '2']
2021-02-20 15:20:28 INFO iou_vm.py:560 IOU instance 21dd9f92-3916-4d07-8460-c7effcf0f42c started PID=55230
2021-02-20 15:20:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:28 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/21dd9f92-3916-4d07-8460-c7effcf0f42c/start HTTP/1.1" 200 952 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:20:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:28 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/21dd9f92-3916-4d07-8460-c7effcf0f42c/start HTTP/1.1" 200 6148 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:20:29 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:29 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:20:36 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/21dd9f92-3916-4d07-8460-c7effcf0f42c/startup-config.cfg
2021-02-20 15:20:37 INFO web_log.py:233 ::1 [20/Feb/2021:10:20:37 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:25:30 INFO iou_vm.py:975 IOU "IOU1" [5494a721-607d-408b-a3c9-99cc0502931d]: NIO UDP removed from 0/0
2021-02-20 15:25:30 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:30 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5494a721-607d-408b-a3c9-99cc0502931d/adapters/0/ports/0/nio HTTP/1.1" 204 296 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:30 INFO cloud.py:449 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: NIO NIO UDP removed from port 0
2021-02-20 15:25:30 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:25:30 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/adapters/0/ports/0/nio HTTP/1.1" 204 296 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:30 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:30 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/180f3fb4-cca1-42e4-a780-404222dd4dd5 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:25:41 INFO base_node.py:331 IOU: 'IOU1' [5494a721-607d-408b-a3c9-99cc0502931d]: is closing
2021-02-20 15:25:41 INFO base_node.py:669 Stopping uBridge hypervisor localhost:44311
2021-02-20 15:25:41 INFO hypervisor.py:208 Stopping uBridge process PID=52846
2021-02-20 15:25:41 INFO base_node.py:331 IOU: 'IOU2' [21dd9f92-3916-4d07-8460-c7effcf0f42c]: is closing
2021-02-20 15:25:41 INFO base_node.py:669 Stopping uBridge hypervisor localhost:37399
2021-02-20 15:25:41 INFO hypervisor.py:208 Stopping uBridge process PID=55225
2021-02-20 15:25:41 INFO iou_vm.py:698 Stopping IOU process for IOU VM "IOU1" PID=52851
2021-02-20 15:25:41 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2021-02-20 15:25:41 ERROR route.py:222 Image missing error detected: /home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin
2021-02-20 15:25:41 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:09:16:35 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 409 695 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:41 ERROR compute.py:452 Error received on compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws': Received fragmented control frame
2021-02-20 15:25:41 INFO compute.py:460 Connection closed to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-02-20 15:25:41 INFO iou_vm.py:698 Stopping IOU process for IOU VM "IOU1" PID=52851
2021-02-20 15:25:41 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/startup-config.cfg
2021-02-20 15:25:41 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/5494a721-607d-408b-a3c9-99cc0502931d/private-config.cfg
2021-02-20 15:25:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:41 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5494a721-607d-408b-a3c9-99cc0502931d HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:41 INFO iou_vm.py:698 Stopping IOU process for IOU VM "IOU2" PID=55230
2021-02-20 15:25:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:41 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5494a721-607d-408b-a3c9-99cc0502931d HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:25:41 INFO iou_vm.py:698 Stopping IOU process for IOU VM "IOU2" PID=55230
2021-02-20 15:25:41 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/21dd9f92-3916-4d07-8460-c7effcf0f42c/startup-config.cfg
2021-02-20 15:25:41 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:25:41 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/21dd9f92-3916-4d07-8460-c7effcf0f42c HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:41 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/21dd9f92-3916-4d07-8460-c7effcf0f42c HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:25:42 INFO compute.py:364 Connecting to compute 'local'
2021-02-20 15:25:42 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:42 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:42 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-02-20 15:25:42 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-02-20 15:25:42 INFO iou_vm.py:73 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: assigned with application ID 1
2021-02-20 15:25:42 INFO iou_vm.py:848 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: number of Ethernet adapters changed to 2
2021-02-20 15:25:42 INFO iou_vm.py:876 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: number of Serial adapters changed to 2
2021-02-20 15:25:42 INFO iou_vm.py:316 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: NVRAM updated from 128KB to 16KB
2021-02-20 15:25:42 INFO iou_vm.py:848 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: number of Ethernet adapters changed to 4
2021-02-20 15:25:42 INFO iou_vm.py:876 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: number of Serial adapters changed to 0
2021-02-20 15:25:42 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:42 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 862 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:42 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:42 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/2d17c91c-ad2a-4874-bc5f-f01a6dde9b18 HTTP/1.1" 201 5993 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:25:42 INFO iou_vm.py:145 IOU "IOU1" [ed0a4cd9-947d-4c32-859b-a20857a0de52]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin"
2021-02-20 15:25:42 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:25:42 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/ed0a4cd9-947d-4c32-859b-a20857a0de52 HTTP/1.1" 200 867 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:25:42 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:42 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/ed0a4cd9-947d-4c32-859b-a20857a0de52 HTTP/1.1" 200 6065 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:25:43 INFO web_log.py:233 ::1 [20/Feb/2021:10:25:43 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:26:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:26:44 +0000] "PUT /v2/templates/2d17c91c-ad2a-4874-bc5f-f01a6dde9b18 HTTP/1.1" 200 871 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:00 INFO iou_vm.py:73 IOU "R2" [46adf105-843d-457d-9488-56e56ce2c4fc]: assigned with application ID 2
2021-02-20 15:27:00 INFO iou_vm.py:848 IOU "R2" [46adf105-843d-457d-9488-56e56ce2c4fc]: number of Ethernet adapters changed to 2
2021-02-20 15:27:00 INFO iou_vm.py:876 IOU "R2" [46adf105-843d-457d-9488-56e56ce2c4fc]: number of Serial adapters changed to 2
2021-02-20 15:27:00 INFO iou_vm.py:316 IOU "R2" [46adf105-843d-457d-9488-56e56ce2c4fc]: NVRAM updated from 128KB to 64KB
2021-02-20 15:27:00 INFO iou_vm.py:145 IOU "R2" [46adf105-843d-457d-9488-56e56ce2c4fc]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 15:27:00 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 865 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:00 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:00 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/34cf1803-742f-4c79-8ba2-49a052717ac0 HTTP/1.1" 201 6703 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:00 INFO iou_vm.py:145 IOU "R2" [46adf105-843d-457d-9488-56e56ce2c4fc]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-02-20 15:27:00 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:27:00 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/46adf105-843d-457d-9488-56e56ce2c4fc HTTP/1.1" 200 870 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:00 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:00 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/46adf105-843d-457d-9488-56e56ce2c4fc HTTP/1.1" 200 6776 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:17 INFO base_node.py:331 IOU: 'IOU1' [ed0a4cd9-947d-4c32-859b-a20857a0de52]: is closing
2021-02-20 15:27:17 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:17 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/ed0a4cd9-947d-4c32-859b-a20857a0de52 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:17 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:17 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/ed0a4cd9-947d-4c32-859b-a20857a0de52 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:23 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:23 +0000] "PUT /v2/templates/2d17c91c-ad2a-4874-bc5f-f01a6dde9b18 HTTP/1.1" 200 871 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:28 INFO iou_vm.py:73 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: assigned with application ID 1
2021-02-20 15:27:28 INFO iou_vm.py:848 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: number of Ethernet adapters changed to 2
2021-02-20 15:27:28 INFO iou_vm.py:876 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: number of Serial adapters changed to 2
2021-02-20 15:27:28 INFO iou_vm.py:316 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: NVRAM updated from 128KB to 16KB
2021-02-20 15:27:28 INFO iou_vm.py:848 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: number of Ethernet adapters changed to 4
2021-02-20 15:27:28 INFO iou_vm.py:876 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: number of Serial adapters changed to 0
2021-02-20 15:27:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:28 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 860 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:28 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/2d17c91c-ad2a-4874-bc5f-f01a6dde9b18 HTTP/1.1" 201 5988 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:28 INFO iou_vm.py:145 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin"
2021-02-20 15:27:28 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:27:28 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067 HTTP/1.1" 200 865 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:28 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067 HTTP/1.1" 200 6061 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:29 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:29 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:30 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp_pnwdj8k/iourc'
2021-02-20 15:27:30 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38829
2021-02-20 15:27:30 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:38829']
2021-02-20 15:27:30 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/ubridge.log
2021-02-20 15:27:30 INFO hypervisor.py:179 ubridge started PID=55481
2021-02-20 15:27:30 INFO base_node.py:658 Hypervisor localhost:38829 has successfully started
2021-02-20 15:27:30 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38829 after 0.1023 seconds
2021-02-20 15:27:30 INFO iou_vm.py:753 IOU S2 [id=5e1151bb-c1b4-4495-83e7-80db4c5d2067]: NETMAP file created
2021-02-20 15:27:30 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin', '-e', '4', '-s', '0', '1']
2021-02-20 15:27:30 INFO iou_vm.py:560 IOU instance 5e1151bb-c1b4-4495-83e7-80db4c5d2067 started PID=55486
2021-02-20 15:27:30 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:30 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067/start HTTP/1.1" 200 950 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:30 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:30 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067/start HTTP/1.1" 200 6146 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:31 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:31 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:38 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/startup-config.cfg
2021-02-20 15:27:39 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:39 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:27:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:44 INFO iou_vm.py:902 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: NIO UDP added to 0/0
2021-02-20 15:27:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:44 INFO cloud.py:396 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: NIO NIO UDP bound to port 0
2021-02-20 15:27:44 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:27:44 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:27:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:44 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:44 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0eb6f96-95a6-4679-83ed-222f77ffe660 HTTP/1.1" 201 1290 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:27:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:27:44 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0eb6f96-95a6-4679-83ed-222f77ffe660 HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:28:40 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/startup-config.cfg
2021-02-20 15:28:40 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/private-config.cfg
2021-02-20 15:28:41 INFO web_log.py:233 ::1 [20/Feb/2021:10:28:41 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:30:33 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/startup-config.cfg
2021-02-20 15:30:33 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/private-config.cfg
2021-02-20 15:30:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:33 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:30:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:54 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0eb6f96-95a6-4679-83ed-222f77ffe660 HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:30:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:54 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0eb6f96-95a6-4679-83ed-222f77ffe660 HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:30:59 INFO base_node.py:331 IOU: 'R2' [46adf105-843d-457d-9488-56e56ce2c4fc]: is closing
2021-02-20 15:30:59 INFO iou_vm.py:975 IOU "S2" [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: NIO UDP removed from 0/0
2021-02-20 15:30:59 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067/adapters/0/ports/0/nio HTTP/1.1" 204 296 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:30:59 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/46adf105-843d-457d-9488-56e56ce2c4fc HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:30:59 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/46adf105-843d-457d-9488-56e56ce2c4fc HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:30:59 INFO cloud.py:449 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: NIO NIO UDP removed from port 0
2021-02-20 15:30:59 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74/adapters/0/ports/0/nio HTTP/1.1" 204 296 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:30:59 INFO base_node.py:331 Builtin: 'NAT2' [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74]: is closing
2021-02-20 15:30:59 INFO base_node.py:669 Stopping uBridge hypervisor localhost:39613
2021-02-20 15:30:59 INFO hypervisor.py:208 Stopping uBridge process PID=50991
2021-02-20 15:30:59 INFO base_node.py:331 IOU: 'S2' [5e1151bb-c1b4-4495-83e7-80db4c5d2067]: is closing
2021-02-20 15:30:59 INFO base_node.py:669 Stopping uBridge hypervisor localhost:38829
2021-02-20 15:30:59 INFO hypervisor.py:208 Stopping uBridge process PID=55481
2021-02-20 15:30:59 INFO iou_vm.py:698 Stopping IOU process for IOU VM "S2" PID=55486
2021-02-20 15:30:59 INFO iou_vm.py:698 Stopping IOU process for IOU VM "S2" PID=55486
2021-02-20 15:30:59 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/startup-config.cfg
2021-02-20 15:30:59 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/ntp/project-files/iou/5e1151bb-c1b4-4495-83e7-80db4c5d2067/private-config.cfg
2021-02-20 15:30:59 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:30:59 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/5e1151bb-c1b4-4495-83e7-80db4c5d2067 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:30:59 INFO cloud.py:248 Cloud "NAT2" [a13a9e0d-e7ef-4403-9bd9-b54c634e5f74] has been closed
2021-02-20 15:30:59 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74 HTTP/1.1" 204 238 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:30:59 INFO web_log.py:233 ::1 [20/Feb/2021:10:30:59 +0000] "DELETE /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/a13a9e0d-e7ef-4403-9bd9-b54c634e5f74 HTTP/1.1" 204 226 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:00 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:00 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:07 INFO docker_vm.py:1058 Docker container "debian-2" [be223251-e468-427b-8de0-c6e0e28120ac]: number of Ethernet adapters changed to 1
2021-02-20 15:31:07 INFO docker_vm.py:406 Docker container 'debian-2' [be223251-e468-427b-8de0-c6e0e28120ac] created
2021-02-20 15:31:07 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:07 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes HTTP/1.1" 201 919 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:07 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:07 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/d9eb10a9-711b-44a6-915f-b1e6dcd2423e HTTP/1.1" 201 1891 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:07 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:07 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac HTTP/1.1" 200 924 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:07 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:07 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac HTTP/1.1" 200 1964 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:08 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:08 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac HTTP/1.1" 200 924 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:08 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:08 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac HTTP/1.1" 200 1964 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:08 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:08 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:11 INFO iou_vm.py:73 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: assigned with application ID 1
2021-02-20 15:31:11 INFO iou_vm.py:848 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: number of Ethernet adapters changed to 2
2021-02-20 15:31:11 INFO iou_vm.py:876 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: number of Serial adapters changed to 2
2021-02-20 15:31:11 INFO iou_vm.py:316 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: NVRAM updated from 128KB to 16KB
2021-02-20 15:31:11 INFO iou_vm.py:848 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: number of Ethernet adapters changed to 4
2021-02-20 15:31:11 INFO iou_vm.py:876 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: number of Serial adapters changed to 0
2021-02-20 15:31:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:11 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes HTTP/1.1" 201 860 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:11 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/2d17c91c-ad2a-4874-bc5f-f01a6dde9b18 HTTP/1.1" 201 5989 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:11 INFO iou_vm.py:145 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin"
2021-02-20 15:31:11 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:11 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398 HTTP/1.1" 200 865 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:11 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398 HTTP/1.1" 200 6062 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:12 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:12 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:12 INFO iou_vm.py:145 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin"
2021-02-20 15:31:12 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:12 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398 HTTP/1.1" 200 865 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:12 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:12 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398 HTTP/1.1" 200 6062 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:19 INFO nat.py:51 NAT node 'NAT2' configured to use NAT interface 'virbr0'
2021-02-20 15:31:19 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38205
2021-02-20 15:31:19 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:38205']
2021-02-20 15:31:19 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/builtin/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49/ubridge.log
2021-02-20 15:31:19 INFO hypervisor.py:179 ubridge started PID=56046
2021-02-20 15:31:19 INFO base_node.py:658 Hypervisor localhost:38205 has successfully started
2021-02-20 15:31:19 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38205 after 0.1031 seconds
2021-02-20 15:31:19 INFO cloud.py:215 Cloud "NAT2" [9f5d31c6-dfc2-4938-a196-2ce5ef82cc49] has been created
2021-02-20 15:31:19 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:19 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:19 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:19 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/templates/df8f4ea9-33b7-3e96-86a2-c39bc9bb649c HTTP/1.1" 201 1574 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:19 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:19 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:19 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:19 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49 HTTP/1.1" 200 1647 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:19 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:19 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:19 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:19 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49 HTTP/1.1" 200 1647 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:20 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:20 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:20 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:20 +0000] "PUT /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:20 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:20 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49 HTTP/1.1" 200 1647 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:28 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:28 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:28 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:28 INFO iou_vm.py:902 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: NIO UDP added to 0/0
2021-02-20 15:31:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:28 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:28 INFO cloud.py:396 Cloud "NAT2" [9f5d31c6-dfc2-4938-a196-2ce5ef82cc49]: NIO NIO UDP bound to port 0
2021-02-20 15:31:28 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:28 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:28 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:28 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/997b28eb-14d4-4677-b9bd-c90269b1024d HTTP/1.1" 201 1290 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:28 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:28 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/997b28eb-14d4-4677-b9bd-c90269b1024d HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:33 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:33 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:33 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:33 INFO iou_vm.py:902 IOU "S2" [d006611a-6f7e-427c-a659-e01bfa1bb398]: NIO UDP added to 2/2
2021-02-20 15:31:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:33 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398/adapters/2/ports/2/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:33 INFO docker_vm.py:960 Docker container 'debian-2' [be223251-e468-427b-8de0-c6e0e28120ac]: NIO UDP added to adapter 0
2021-02-20 15:31:33 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:33 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:33 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:33 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/86f95cb8-030a-47b7-99e0-765a00b3db35 HTTP/1.1" 201 1291 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:33 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:33 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/86f95cb8-030a-47b7-99e0-765a00b3db35 HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:36 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp__byeg75/iourc'
2021-02-20 15:31:36 INFO base_node.py:655 Starting new uBridge hypervisor localhost:39929
2021-02-20 15:31:36 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:39929']
2021-02-20 15:31:36 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/d006611a-6f7e-427c-a659-e01bfa1bb398/ubridge.log
2021-02-20 15:31:36 INFO hypervisor.py:179 ubridge started PID=56084
2021-02-20 15:31:36 INFO base_node.py:658 Hypervisor localhost:39929 has successfully started
2021-02-20 15:31:36 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:39929 after 0.1030 seconds
2021-02-20 15:31:36 INFO iou_vm.py:753 IOU S2 [id=d006611a-6f7e-427c-a659-e01bfa1bb398]: NETMAP file created
2021-02-20 15:31:36 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin', '-e', '4', '-s', '0', '1']
2021-02-20 15:31:36 INFO iou_vm.py:560 IOU instance d006611a-6f7e-427c-a659-e01bfa1bb398 started PID=56089
2021-02-20 15:31:36 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:36 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398/start HTTP/1.1" 200 950 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:36 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:36 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398/start HTTP/1.1" 200 6147 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:40 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:40 +0000] "GET /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac/files/etc/network/interfaces HTTP/1.1" 200 574 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:44 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/d006611a-6f7e-427c-a659-e01bfa1bb398/startup-config.cfg
2021-02-20 15:31:44 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:44 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:46 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:31:46 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/files/project-files/docker/be223251-e468-427b-8de0-c6e0e28120ac/etc/network/interfaces HTTP/1.1" 200 226 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:46 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:46 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac/files/etc/network/interfaces HTTP/1.1" 201 239 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:48 INFO base_node.py:655 Starting new uBridge hypervisor localhost:41045
2021-02-20 15:31:48 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:41045']
2021-02-20 15:31:48 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/docker/be223251-e468-427b-8de0-c6e0e28120ac/ubridge.log
2021-02-20 15:31:48 INFO hypervisor.py:179 ubridge started PID=56158
2021-02-20 15:31:48 INFO base_node.py:658 Hypervisor localhost:41045 has successfully started
2021-02-20 15:31:48 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:41045 after 0.1027 seconds
2021-02-20 15:31:48 INFO docker_vm.py:499 Docker container 'debian-2' [debian:latest] started listen for telnet on 5003
2021-02-20 15:31:48 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:48 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:31:48 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:48 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac/start HTTP/1.1" 200 1970 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:49 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:49 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:53 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:53 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:53 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:53 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:53 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:53 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/86f95cb8-030a-47b7-99e0-765a00b3db35 HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:53 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/86f95cb8-030a-47b7-99e0-765a00b3db35 HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:53 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0fd77f5-337b-4511-972c-799bf9d8fb9c HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:53 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0fd77f5-337b-4511-972c-799bf9d8fb9c HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:54 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/279ab14c-c9c9-4366-b5df-fdbde6e2ca5b HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:31:54 INFO web_log.py:233 ::1 [20/Feb/2021:10:31:54 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/279ab14c-c9c9-4366-b5df-fdbde6e2ca5b HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:00 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/63b15396-0475-4fc0-9f21-56892248ce0f/stop HTTP/1.1" 204 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:00 INFO base_node.py:669 Stopping uBridge hypervisor localhost:38313
2021-02-20 15:32:00 INFO hypervisor.py:208 Stopping uBridge process PID=22589
2021-02-20 15:32:00 INFO base_node.py:669 Stopping uBridge hypervisor localhost:41489
2021-02-20 15:32:00 INFO hypervisor.py:208 Stopping uBridge process PID=22606
2021-02-20 15:32:00 INFO base_node.py:669 Stopping uBridge hypervisor localhost:34629
2021-02-20 15:32:00 INFO hypervisor.py:208 Stopping uBridge process PID=22494
2021-02-20 15:32:00 INFO qemu_vm.py:1084 Stopping QEMU VM "R1" PID=22602
2021-02-20 15:32:00 INFO qemu_vm.py:1068 QEMU process has stopped, return code: 0
2021-02-20 15:32:00 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/stop HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:00 INFO base_node.py:669 Stopping uBridge hypervisor localhost:41045
2021-02-20 15:32:00 INFO hypervisor.py:208 Stopping uBridge process PID=56158
2021-02-20 15:32:00 INFO docker_vm.py:533 Docker container 'debian-2' fix ownership, state = running
2021-02-20 15:32:00 INFO qemu_vm.py:1084 Stopping QEMU VM "S1" PID=22574
2021-02-20 15:32:00 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = running
2021-02-20 15:32:01 INFO qemu_vm.py:1068 QEMU process has stopped, return code: 0
2021-02-20 15:32:01 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/stop HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:01 INFO base_node.py:669 Stopping uBridge hypervisor localhost:39929
2021-02-20 15:32:01 INFO hypervisor.py:208 Stopping uBridge process PID=56084
2021-02-20 15:32:01 INFO docker_vm.py:793 Docker container 'debian-2' [debian:latest] stopped
2021-02-20 15:32:01 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:01 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:01 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49/stop HTTP/1.1" 204 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:01 INFO docker_vm.py:793 Docker container 'debian-1' [debian:latest] stopped
2021-02-20 15:32:01 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:00 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:01 INFO iou_vm.py:698 Stopping IOU process for IOU VM "S2" PID=56089
2021-02-20 15:32:01 INFO iou_vm.py:698 Stopping IOU process for IOU VM "S2" PID=56089
2021-02-20 15:32:01 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/ntp/project-files/iou/d006611a-6f7e-427c-a659-e01bfa1bb398/startup-config.cfg
2021-02-20 15:32:01 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:01 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398/stop HTTP/1.1" 204 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:01 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:00 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/stop HTTP/1.1" 204 221 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:01 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:01 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:02 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:02 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0fd77f5-337b-4511-972c-799bf9d8fb9c HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:02 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:02 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a0fd77f5-337b-4511-972c-799bf9d8fb9c HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:02 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:02 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/279ab14c-c9c9-4366-b5df-fdbde6e2ca5b HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:02 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:02 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:02 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:02 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/279ab14c-c9c9-4366-b5df-fdbde6e2ca5b HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:10 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:10 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/63b15396-0475-4fc0-9f21-56892248ce0f/start HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:10 INFO qemu_vm.py:1621 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/qemu-img.log
2021-02-20 15:32:10 INFO qemu_vm.py:1623 Executing qemu-img with: /usr/sbin/qemu-img check /home/saad/GNS3/images/QEMU/vios-adventerprisek9-m.vmdk.SPA.156-2.T
2021-02-20 15:32:10 INFO qemu_vm.py:1621 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/qemu-img.log
2021-02-20 15:32:10 INFO qemu_vm.py:1623 Executing qemu-img with: /bin/qemu-img check /home/saad/GNS3/images/QEMU/vios_l2-adventerprisek9-m.03.2017.qcow2
2021-02-20 15:32:11 INFO qemu_vm.py:1627 /usr/sbin/qemu-img returned with 0
2021-02-20 15:32:11 INFO qemu_vm.py:1627 /bin/qemu-img returned with 0
2021-02-20 15:32:11 INFO qemu_vm.py:1621 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/qemu-img.log
2021-02-20 15:32:11 INFO qemu_vm.py:1623 Executing qemu-img with: /usr/sbin/qemu-img check /home/saad/GNS3/images/QEMU/IOSv_startup_config.img
2021-02-20 15:32:11 INFO qemu_vm.py:1627 /usr/sbin/qemu-img returned with 63
2021-02-20 15:32:11 INFO qemu_vm.py:1011 Starting QEMU with: /bin/qemu-system-x86_64 -name S1 -m 768M -smp cpus=1,sockets=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/hda_disk.qcow2,if=ide,index=0,media=disk,id=drive0 -uuid 73b6d391-5e52-4114-8286-8936a2e5d082 -serial telnet:127.0.0.1:5000,server,nowait -monitor tcp:127.0.0.1:45293,server,nowait -net none -device e1000,mac=0c:49:55:d0:82:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -device e1000,mac=0c:49:55:d0:82:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10009,localaddr=127.0.0.1:10008 -device e1000,mac=0c:49:55:d0:82:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10011,localaddr=127.0.0.1:10010 -device e1000,mac=0c:49:55:d0:82:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10013,localaddr=127.0.0.1:10012 -device e1000,mac=0c:49:55:d0:82:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10015,localaddr=127.0.0.1:10014 -device e1000,mac=0c:49:55:d0:82:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:49:55:d0:82:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:49:55:d0:82:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -display none
2021-02-20 15:32:11 INFO qemu_vm.py:1013 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/qemu.log
2021-02-20 15:32:11 INFO qemu_vm.py:1021 QEMU VM "S1" started PID=56500
2021-02-20 15:32:11 INFO base_node.py:655 Starting new uBridge hypervisor localhost:35693
2021-02-20 15:32:11 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:35693']
2021-02-20 15:32:11 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/73b6d391-5e52-4114-8286-8936a2e5d082/ubridge.log
2021-02-20 15:32:11 INFO base_node.py:655 Starting new uBridge hypervisor localhost:39901
2021-02-20 15:32:11 INFO hypervisor.py:179 ubridge started PID=56537
2021-02-20 15:32:11 INFO base_node.py:658 Hypervisor localhost:35693 has successfully started
2021-02-20 15:32:11 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:39901']
2021-02-20 15:32:11 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/docker/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/ubridge.log
2021-02-20 15:32:11 INFO hypervisor.py:179 ubridge started PID=56547
2021-02-20 15:32:11 INFO base_node.py:658 Hypervisor localhost:39901 has successfully started
2021-02-20 15:32:11 INFO qemu_vm.py:1011 Starting QEMU with: /usr/sbin/qemu-system-i386 -name R1 -m 512M -smp cpus=1,sockets=1 -enable-kvm -boot order=c -drive file=/home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -drive file=/home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/hdb_disk.qcow2,if=virtio,index=1,media=disk,id=drive1 -uuid b9afaf3b-8404-4fe2-ac5c-75a89a79fa11 -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:35485,server,nowait -net none -device e1000,mac=0c:49:55:fa:11:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -device e1000,mac=0c:49:55:fa:11:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10025,localaddr=127.0.0.1:10024 -device e1000,mac=0c:49:55:fa:11:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10027,localaddr=127.0.0.1:10026 -device e1000,mac=0c:49:55:fa:11:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10029,localaddr=127.0.0.1:10028 -device e1000,mac=0c:49:55:fa:11:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10031,localaddr=127.0.0.1:10030 -device e1000,mac=0c:49:55:fa:11:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10033,localaddr=127.0.0.1:10032 -device e1000,mac=0c:49:55:fa:11:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10035,localaddr=127.0.0.1:10034 -device e1000,mac=0c:49:55:fa:11:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10037,localaddr=127.0.0.1:10036 -display none
2021-02-20 15:32:11 INFO qemu_vm.py:1013 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/qemu.log
2021-02-20 15:32:11 INFO qemu_vm.py:1021 QEMU VM "R1" started PID=56553
2021-02-20 15:32:11 INFO base_node.py:655 Starting new uBridge hypervisor localhost:34963
2021-02-20 15:32:11 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:34963']
2021-02-20 15:32:11 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/qemu/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/ubridge.log
2021-02-20 15:32:11 INFO hypervisor.py:179 ubridge started PID=56557
2021-02-20 15:32:11 INFO base_node.py:658 Hypervisor localhost:34963 has successfully started
2021-02-20 15:32:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:35693 after 0.1022 seconds
2021-02-20 15:32:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:39901 after 0.1020 seconds
2021-02-20 15:32:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:34963 after 0.1019 seconds
2021-02-20 15:32:11 INFO qemu_vm.py:1147 Connected to QEMU monitor on 127.0.0.1:45293 after 0.0123 seconds
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-2 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-3 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-4 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-5 off
2021-02-20 15:32:11 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5012
2021-02-20 15:32:11 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:10 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-6 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-7 off
2021-02-20 15:32:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:10 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/start HTTP/1.1" 200 3055 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:11 INFO qemu_vm.py:1147 Connected to QEMU monitor on 127.0.0.1:35485 after 0.0159 seconds
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-2 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-3 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-4 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-5 off
2021-02-20 15:32:11 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp__byeg75/iourc'
2021-02-20 15:32:11 INFO base_node.py:655 Starting new uBridge hypervisor localhost:36169
2021-02-20 15:32:11 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:36169']
2021-02-20 15:32:11 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/iou/d006611a-6f7e-427c-a659-e01bfa1bb398/ubridge.log
2021-02-20 15:32:11 INFO hypervisor.py:179 ubridge started PID=56662
2021-02-20 15:32:11 INFO base_node.py:658 Hypervisor localhost:36169 has successfully started
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-6 off
2021-02-20 15:32:11 INFO qemu_vm.py:1212 Execute QEMU monitor command: set_link gns3-7 off
2021-02-20 15:32:11 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:10 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/start HTTP/1.1" 200 3347 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:11 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/nat/nodes/9f5d31c6-dfc2-4938-a196-2ce5ef82cc49/start HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:11 INFO base_node.py:655 Starting new uBridge hypervisor localhost:40369
2021-02-20 15:32:11 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:40369']
2021-02-20 15:32:11 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/docker/be223251-e468-427b-8de0-c6e0e28120ac/ubridge.log
2021-02-20 15:32:11 INFO hypervisor.py:179 ubridge started PID=56701
2021-02-20 15:32:11 INFO base_node.py:658 Hypervisor localhost:40369 has successfully started
2021-02-20 15:32:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:11 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:36169 after 0.1026 seconds
2021-02-20 15:32:11 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:40369 after 0.1020 seconds
2021-02-20 15:32:11 INFO iou_vm.py:753 IOU S2 [id=d006611a-6f7e-427c-a659-e01bfa1bb398]: NETMAP file created
2021-02-20 15:32:11 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.2a.bin', '-e', '4', '-s', '0', '1']
2021-02-20 15:32:11 INFO iou_vm.py:560 IOU instance d006611a-6f7e-427c-a659-e01bfa1bb398 started PID=56724
2021-02-20 15:32:11 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:11 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/iou/nodes/d006611a-6f7e-427c-a659-e01bfa1bb398/start HTTP/1.1" 200 950 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:11 INFO docker_vm.py:499 Docker container 'debian-2' [debian:latest] started listen for telnet on 5003
2021-02-20 15:32:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:11 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:11 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:10 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/start HTTP/1.1" 204 222 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:12 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:12 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:14 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:13 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/86f95cb8-030a-47b7-99e0-765a00b3db35 HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:14 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:13 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/997b28eb-14d4-4677-b9bd-c90269b1024d HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:14 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:14 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/997b28eb-14d4-4677-b9bd-c90269b1024d HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:14 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:14 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/86f95cb8-030a-47b7-99e0-765a00b3db35 HTTP/1.1" 201 1373 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:18 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:18 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:18 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:18 +0000] "PUT /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/links/a23b6104-68ef-45dd-86e9-4e860105a8ca HTTP/1.1" 201 1372 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:18 INFO base_node.py:669 Stopping uBridge hypervisor localhost:35693
2021-02-20 15:32:18 INFO hypervisor.py:208 Stopping uBridge process PID=56537
2021-02-20 15:32:18 INFO base_node.py:669 Stopping uBridge hypervisor localhost:39901
2021-02-20 15:32:18 INFO hypervisor.py:208 Stopping uBridge process PID=56547
2021-02-20 15:32:18 INFO qemu_vm.py:1084 Stopping QEMU VM "S1" PID=56500
2021-02-20 15:32:18 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = running
2021-02-20 15:32:18 INFO qemu_vm.py:1068 QEMU process has stopped, return code: 0
2021-02-20 15:32:18 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:18 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/stop HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:18 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:18 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/73b6d391-5e52-4114-8286-8936a2e5d082/stop HTTP/1.1" 200 6787 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:18 INFO docker_vm.py:793 Docker container 'debian-1' [debian:latest] stopped
2021-02-20 15:32:18 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:18 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:18 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:18 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/0e0f6f7c-2acd-4d08-a657-ea4121d2cfed/stop HTTP/1.1" 200 1967 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:19 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:19 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:21 INFO base_node.py:669 Stopping uBridge hypervisor localhost:34963
2021-02-20 15:32:21 INFO hypervisor.py:208 Stopping uBridge process PID=56557
2021-02-20 15:32:21 INFO qemu_vm.py:1084 Stopping QEMU VM "R1" PID=56553
2021-02-20 15:32:21 INFO qemu_vm.py:1068 QEMU process has stopped, return code: 0
2021-02-20 15:32:21 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:21 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/qemu/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/stop HTTP/1.1" 204 244 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:21 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:21 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/b9afaf3b-8404-4fe2-ac5c-75a89a79fa11/stop HTTP/1.1" 200 7070 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:36 INFO base_node.py:669 Stopping uBridge hypervisor localhost:40369
2021-02-20 15:32:36 INFO hypervisor.py:208 Stopping uBridge process PID=56701
2021-02-20 15:32:36 INFO docker_vm.py:533 Docker container 'debian-2' fix ownership, state = running
2021-02-20 15:32:36 INFO docker_vm.py:793 Docker container 'debian-2' [debian:latest] stopped
2021-02-20 15:32:36 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:36 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:36 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:36 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac/stop HTTP/1.1" 200 1969 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:37 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:37 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:32:38 INFO base_node.py:655 Starting new uBridge hypervisor localhost:41533
2021-02-20 15:32:38 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:41533']
2021-02-20 15:32:38 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/ntp/project-files/docker/be223251-e468-427b-8de0-c6e0e28120ac/ubridge.log
2021-02-20 15:32:38 INFO hypervisor.py:179 ubridge started PID=57015
2021-02-20 15:32:38 INFO base_node.py:658 Hypervisor localhost:41533 has successfully started
2021-02-20 15:32:38 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:41533 after 0.1026 seconds
2021-02-20 15:32:38 INFO docker_vm.py:499 Docker container 'debian-2' [debian:latest] started listen for telnet on 5003
2021-02-20 15:32:38 INFO web_log.py:233 127.0.0.1 [20/Feb/2021:10:32:38 +0000] "POST /v2/compute/projects/54200cb8-26b8-4929-8b2b-553020004955/docker/nodes/be223251-e468-427b-8de0-c6e0e28120ac/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-02-20 15:32:38 INFO web_log.py:233 ::1 [20/Feb/2021:10:32:38 +0000] "POST /v2/projects/54200cb8-26b8-4929-8b2b-553020004955/nodes/be223251-e468-427b-8de0-c6e0e28120ac/start HTTP/1.1" 200 1970 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:33:58 INFO web_log.py:233 ::1 [20/Feb/2021:10:33:58 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.17"
2021-02-20 15:42:25 INFO web_log.py:233 ::1 [20/Feb/2021:10:42:25 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.17"
